# Generated by Django 3.2.25 on 2026-01-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
