# Generated by Django 3.2.25 on 2026-01-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20260130_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='specilaizations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='timings',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='timings',
            name='name',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='patient',
        ),
        migrations.DeleteModel(
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Timings',
        ),
    ]
