# Generated by Django 3.2.25 on 2026-01-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timings',
            old_name='slots',
            new_name='starttime',
        ),
        migrations.AddField(
            model_name='timings',
            name='endtime',
            field=models.TimeField(default='2:00'),
            preserve_default=False,
        ),
    ]
