# Generated by Django 3.2.25 on 2026-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='endtime',
            field=models.DateTimeField(),
        ),
    ]
