# Generated by Django 3.2.25 on 2026-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_alter_timings_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timings',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
